/* Generated By:JavaCC: Do not edit this line. Compiler.java */
package grammaire;

public class Compiler implements CompilerConstants {
  /** Compilation d'un fichier de combattant  * @param s : le nom du fichier  * @throws Exception une erreur de lecture  */
  public static void compile(String s) throws Exception
  {
    FileReader r = new FileReader(s);
    Compiler parser = new Compiler(new BufferedReader(r));
    ArrayList < Instruction > code = parser.INSTRUCTIONS();
    /*Return une liste d'instructions? */
  }

  /** réalignement en cas d’erreur de syntaxe sur le symbole EOL*/
  private void skiptoEOL()
  {
    while (token.kind != EOL || token.kind != CEOL) getNextToken();
  }

//  les règles de grammaire de ce langage   final public List < Instruction > INSTRUCTIONS() throws ParseException {
  ArrayList < Instruction > inst = new ArrayList();
  Instruction courante;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DAT:
      case MOV:
      case ADD:
      case SUB:
      case MUL:
      case DIV:
      case MOD:
      case JMP:
      case JMZ:
      case JMN:
      case DJN:
      case CMP:
      case CLT:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      courante = INSTRUCTION();
      jj_consume_token(EOL);
      inst.add(courante);
    }
    jj_consume_token(0);
    {if (true) return inst;}
    throw new Error("Missing return statement in function");
  }

  final public Instruction INSTRUCTION() throws ParseException, Exception {
  Token operation;
  Operande operande1;
  Operande operande2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DAT:
      operation = jj_consume_token(DAT);
      operande1 = operande();

      break;
    case MOV:
      operation = jj_consume_token(MOV);
      operande1 = operande();
      operande2 = operande();

      break;
    case ADD:
      operation = jj_consume_token(ADD);
      operande1 = operande();
      operande2 = operande();
   {if (true) return new Add(operande1, operande2);}
      break;
    case SUB:
      operation = jj_consume_token(SUB);
      operande1 = operande();
      operande2 = operande();

      break;
    case MUL:
      operation = jj_consume_token(MUL);
      operande1 = operande();
      operande2 = operande();

      break;
    case DIV:
      operation = jj_consume_token(DIV);
      operande1 = operande();
      operande2 = operande();

      break;
    case MOD:
      operation = jj_consume_token(MOD);
      operande1 = operande();
      operande2 = operande();

      break;
    case JMP:
      operation = jj_consume_token(JMP);
      operande1 = operande();

      break;
    case JMZ:
      operation = jj_consume_token(JMZ);
      operande1 = operande();
      operande2 = operande();

      break;
    case JMN:
      operation = jj_consume_token(JMN);
      operande1 = operande();
      operande2 = operande();

      break;
    case DJN:
      operation = jj_consume_token(DJN);
      operande1 = operande();
      operande2 = operande();

      break;
    case CMP:
      operation = jj_consume_token(CMP);
      operande1 = operande();
      operande2 = operande();

      break;
    case CLT:
      operation = jj_consume_token(CLT);
      operande1 = operande();
      operande2 = operande();
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public Operande operande() throws ParseException {
  Token op;
  Token val;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IMM:
      op = jj_consume_token(IMM);
      val = jj_consume_token(VALEUR);
      {if (true) return new Operande(new Immediat(),new Integer(val.image));}
      break;
    case NUM:
      op = jj_consume_token(NUM);
      val = jj_consume_token(VALEUR);
      {if (true) return new Operande(new Relatif(),new Integer(val.image));}
      break;
    case IND:
      op = jj_consume_token(IND);
      val = jj_consume_token(VALEUR);
      {if (true) return new Operande(new RelatifIndirect(),new Integer(val.image));}
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public CompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[3];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0xe0000000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x3ffe,0x3ffe,0x0,};
   }

  /** Constructor with InputStream. */
  public Compiler(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compiler(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compiler(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompilerTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compiler(CompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompilerTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 3; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[78];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 3; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 78; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
